spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/hello
    username: sa
    password: 1
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true
          # JPQL 쿼리를 보는 옵션

server:
  port: 8083